---
  # 1. MySQL
  - hosts: database
    become: yes
    vars_files:
      - secrets.yml
    roles:
      - magento_mysql

  # 2. Magento
  - hosts: web
    become: yes
    vars_files:
      - secrets.yml
      - inventory/group_vars/mysql.yml
      - inventory/group_vars/magento.yml
    roles:
      - magento

  # 3. Nginx
  - hosts: web
    become: yes
    vars_files:
      - secrets.yml
      - inventory/group_vars/mysql.yml
    roles:
      - nginx
