---
  dependency:
    name: galaxy
  driver:
    name: ec2
  platforms:
    - name: instance
      image: fallewi/ansible-molecule:datasientest
      pre_build_image: true
  provisioner:
    name: ansible
  verifier:
    name: testinfra
